name: Mise a jour auto des competitions

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Exécuter le script
        run: python script.py

      - name: Sauvegarder competitions.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add competitions.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour automatique des compétitions" && git push)
